### ISSUE TITLE
Incorrect badge numbers with very small widths

### ISSUE THREAD

**Issue by giantpinkwalrus** [sickdyd/react-dynamic-badge#1]
## What I did
I created a simple app using this(link at the bottom) and set the container width to be very small

## Expected behavior
With very small widths where the container is too small to show any items it should display the total number of items in the badge

## What happened
It showed +3 and Item 1 is invisible to the user.

## Other notes
This will help to solve the issues you were having earlier with the tests(window resizing). I think there's a problem with the asserts rather than the resizing.

## Bug showcase
https://codesandbox.io/s/react-dynamic-badge-bug-showcase-p8jdn

**Comment by sickdyd** [comment]
Thank you for creating a new issue.

Originally the badge was developed to always show at least one item, but of course in this case it will fail.

I will correct the behavior and post an update soon.

**Comment by sickdyd** [comment]
I fixed the issue, you can verify visiting this link:
https://codesandbox.io/s/react-dynamic-badge-bug-showcase-gnp8s

I also added a few props to tweak the badge:

- minWidth: sets the minimum width for the text to be shown; defaults at 1/2 characters depending on the font and character.
- onlyBadge: if set to true it will display only the badge and no text.
